name = "Avery's Essentials"
author = "averythebird"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5dbeb96afd37060bcb2701f36fab017634e47b5f368d04fe69d3b2502ab7097"

[versions]
fabric = "0.16.2"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
