name = "Avery's Essentials"
author = "averythebird"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "810f51f8333896be6e70090ac70f158efa1e3478130d504763fda0a313b0312d"

[versions]
fabric = "0.16.2"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
