name = "Avery's Essentials"
author = "averythebird"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9f717884289236bfed91de80a361dadc600f3b4ac2d19bd8e1adf4f56062ce7"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
