name = "Avery's Essentials"
author = "averythebird"
version = "1.11.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9d33ea9a5e9d1ce3a28840b7be6606e30649761d04530819871eba2c523ae00"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
