name = "Avery's Essentials"
author = "averythebird"
version = "1.11.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0610546efde59c23daa57039ff0e673ddf3be744896c426ffe72a959ba10f2af"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
