name = "Avery's Essentials"
author = "averythebird"
version = "1.11.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afe0c809594999d200dd6a2f0cac0ae71d8d8a2f7741b01ced9015f71693e862"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
